/* Generated by Yosys 0.38+92 (git sha1 84116c9a3, x86_64-conda-linux-gnu-cc 11.2.0 -fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -fdebug-prefix-map=/root/conda-eda/conda-eda/workdir/conda-env/conda-bld/yosys_1708682838165/work=/usr/local/src/conda/yosys-0.38_93_g84116c9a3 -fdebug-prefix-map=/opt/conda/envs/openroad-env=/usr/local/src/conda-prefix -fPIC -Os -fno-merge-constants) */

module counter(clk, rst_n, en, count);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  input clk;
  output [3:0] count;
  input en;
  input rst_n;
  sky130_fd_sc_hd__nand2_1 _07_ (
    .A(count[0]),
    .B(en),
    .Y(_04_)
  );
  sky130_fd_sc_hd__xor2_1 _08_ (
    .A(count[0]),
    .B(en),
    .X(_00_)
  );
  sky130_fd_sc_hd__xnor2_1 _09_ (
    .A(count[1]),
    .B(_04_),
    .Y(_01_)
  );
  sky130_fd_sc_hd__nand4_1 _10_ (
    .A(count[0]),
    .B(count[1]),
    .C(count[2]),
    .D(en),
    .Y(_05_)
  );
  sky130_fd_sc_hd__a31oi_1 _11_ (
    .A1(count[0]),
    .A2(count[1]),
    .A3(en),
    .B1(count[2]),
    .Y(_06_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _12_ (
    .A(_05_),
    .SLEEP(_06_),
    .X(_02_)
  );
  sky130_fd_sc_hd__xnor2_1 _13_ (
    .A(count[3]),
    .B(_05_),
    .Y(_03_)
  );
  sky130_fd_sc_hd__dfrtp_1 _14_ (
    .CLK(clk),
    .D(_00_),
    .Q(count[0]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _15_ (
    .CLK(clk),
    .D(_01_),
    .Q(count[1]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _16_ (
    .CLK(clk),
    .D(_02_),
    .Q(count[2]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _17_ (
    .CLK(clk),
    .D(_03_),
    .Q(count[3]),
    .RESET_B(rst_n)
  );
endmodule
