/* Generated by Yosys 0.38+92 (git sha1 84116c9a3, x86_64-conda-linux-gnu-cc 11.2.0 -fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -fdebug-prefix-map=/root/conda-eda/conda-eda/workdir/conda-env/conda-bld/yosys_1708682838165/work=/usr/local/src/conda/yosys-0.38_93_g84116c9a3 -fdebug-prefix-map=/opt/conda/envs/openroad-env=/usr/local/src/conda-prefix -fPIC -Os -fno-merge-constants) */

(* top =  1  *)
(* src = "/tmp/counter.v:1.1-13.10" *)
module counter(clk, rst, count);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  (* force_downto = 32'd1 *)
  (* src = "/tmp/counter.v:10.22-10.37|/opt/conda/envs/openroad-env/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire [3:0] _06_;
  (* force_downto = 32'd1 *)
  (* src = "/tmp/counter.v:10.22-10.37|/opt/conda/envs/openroad-env/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire [3:0] _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  (* src = "/tmp/counter.v:2.23-2.26" *)
  input clk;
  wire clk;
  (* src = "/tmp/counter.v:4.23-4.28" *)
  output [3:0] count;
  wire [3:0] count;
  (* src = "/tmp/counter.v:3.23-3.26" *)
  input rst;
  wire rst;
  INV_X1 _11_ (
    .A(rst),
    .ZN(_00_)
  );
  NAND2_X1 _12_ (
    .A1(count[0]),
    .A2(count[1]),
    .ZN(_04_)
  );
  XOR2_X1 _13_ (
    .A(count[0]),
    .B(count[1]),
    .Z(_07_[1])
  );
  NAND3_X1 _14_ (
    .A1(count[0]),
    .A2(count[1]),
    .A3(count[2]),
    .ZN(_05_)
  );
  XNOR2_X1 _15_ (
    .A(count[2]),
    .B(_04_),
    .ZN(_07_[2])
  );
  XNOR2_X1 _16_ (
    .A(count[3]),
    .B(_05_),
    .ZN(_07_[3])
  );
  INV_X1 _17_ (
    .A(rst),
    .ZN(_01_)
  );
  INV_X1 _18_ (
    .A(rst),
    .ZN(_02_)
  );
  INV_X1 _19_ (
    .A(rst),
    .ZN(_03_)
  );
  (* src = "/tmp/counter.v:6.5-12.8" *)
  DFFR_X1 _20_ (
    .CK(clk),
    .D(_06_[0]),
    .Q(count[0]),
    .QN(_06_[0]),
    .RN(_00_)
  );
  (* src = "/tmp/counter.v:6.5-12.8" *)
  DFFR_X1 _21_ (
    .CK(clk),
    .D(_07_[1]),
    .Q(count[1]),
    .QN(_10_),
    .RN(_01_)
  );
  (* src = "/tmp/counter.v:6.5-12.8" *)
  DFFR_X1 _22_ (
    .CK(clk),
    .D(_07_[2]),
    .Q(count[2]),
    .QN(_09_),
    .RN(_02_)
  );
  (* src = "/tmp/counter.v:6.5-12.8" *)
  DFFR_X1 _23_ (
    .CK(clk),
    .D(_07_[3]),
    .Q(count[3]),
    .QN(_08_),
    .RN(_03_)
  );
  assign _06_[3:1] = count[3:1];
  assign _07_[0] = _06_[0];
endmodule
